# Python Weekly Assignment
#Topics: Exception Handling · NumPy · Pandas Basics


# Section A — Exception Handling

In [1]:
"""
1. Write a function safe_divide(a, b) that divides two numbers and handles ZeroDivisionError and
TypeError separately, printing an appropriate message for each. Use a finally block to print
'Operation attempted.' regardless of the outcome. Test it with valid numbers, division by zero, and a
string input.

""";

In [32]:
def safe_divide(a,b):
    try:
        c= a/b
        print(c)
        
    except ZeroDivisionError :
        print("Error : zdivision not possiable")
        
    except TypeError :
        print("wrong input")
        
    finally :
        print("Operation attempted.")

In [34]:
safe_divide(2,"10")# String input
safe_divide(13,0)  # Division by zero
safe_divide(10,2) #valid input

wrong input
Operation attempted.
Error : zdivision not possiable
Operation attempted.
5.0
Operation attempted.


In [35]:
"""
2. Write a function validate_age(age) that raises a custom exception InvalidAgeError (a class you
define, inheriting from Exception) if age is negative or greater than 120. Catch this exception in a
calling block and print a user-friendly message. Test it with at least 3 different values.
""";

In [12]:
class Age(Exception):
    pass 
def validate_age(age):
    if age < 0 or age >120 :
        raise Age("Age must be between 0 and 120.")
    print(f"Age = {age} is valid ")
    
test_ages = [25, 130, -5]

for age in test_ages:
    try :
        validate_age(age)
    except Age as e :
        print(f"Invalid age {age}: {e}")

Age = 25 is valid 
Invalid age 130: Age must be between 0 and 120.
Invalid age -5: Age must be between 0 and 120.


In [13]:
"""
3. Write a program that repeatedly asks the user (use a loop with at least 3 simulated inputs in a list,
e.g. user_inputs = ['10', 'abc', '0', '5']) to enter a number and divide 100 by it. Handle the following in
a single try block using multiple except clauses:
a) ValueError if the input is not a number.
b) ZeroDivisionError if the input is zero.
c) A generic Exception as a catch-all for anything else.
Print the result if successful, otherwise print which error occurred.
""";

In [33]:
user_inputs = ['10', 'abc', '0', '5']
for value in user_inputs :
    try :
        num = int(value)
        result = 100/num
        print(f"100 / {num} = {result}")
    except ValueError:
        print(f"The {value} you entered is not int")
    except ZeroDivisionError :
        print("division by zero is not possiable")
    except Exception as e :
        print(f"unexpected error:{e}")

100 / 10 = 10.0
The abc you entered is not int
division by zero is not possiable
100 / 5 = 20.0


# Section B — NumPy


In [34]:
"""
4. Create a 1D NumPy array of integers from 1 to 20. Perform the following:
a) Reshape it into a 4x5 2D array.
b) Print the sum of each row and each column.
c) Extract all elements greater than 10 using boolean indexing.
d) Replace all even numbers in the array with -1.
""";

In [35]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
arr = np.arange(1 , 21)
print(arr)
#a
new_arr = arr.reshape(4,5)
print(new_arr)
#B
print("columns",np.sum(new_arr,axis = 0))
print("ROws =",np.sum(new_arr,axis=1))
#c 
print("\nElements greater than 10:")
print(new_arr[new_arr > 10])
#D
new_arr[new_arr % 2 ==0 ] =-1
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
columns [34 38 42 46 50]
ROws = [15 40 65 90]

Elements greater than 10:
[11 12 13 14 15 16 17 18 19 20]
[[ 1 -1  3 -1  5]
 [-1  7 -1  9 -1]
 [11 -1 13 -1 15]
 [-1 17 -1 19 -1]]


In [41]:
"""
5. Create two NumPy arrays A and B as shown below and perform:
A = np.array([[1, 2], [3, 4]]) B = np.array([[5, 6], [7, 8]])
a) Element-wise addition, subtraction, and multiplication.
b) Matrix multiplication using np.dot() or the @ operator.
c) Transpose of A.
d) The determinant and inverse of A using np.linalg
""";

In [66]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
#Element-wise addition, subtraction, and multiplication.
print("Addition\n",A+B)
print("substraction\n",A-B)
print("Multiplication \n",A*B)

#B Matrix multiplication using np.dot() or the @ operator.
print("matrix multiplication",A @B)

#c Transpose of A.
trans= A.T
print("Transpose of A:\n",trans)

#D d) The determinant and inverse of A using np.linalg
print("Determinant of A:", np.linalg.det(A))
print("Determinant of A:", np.linalg.inv(B))

Addition
 [[ 6  8]
 [10 12]]
substraction
 [[-4 -4]
 [-4 -4]]
Multiplication 
 [[ 5 12]
 [21 32]]
matrix multiplication [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]
Determinant of A: -2.0000000000000004
Determinant of A: -2.0000000000000004


In [67]:
"""
6. Generate a NumPy array of 15 random integers between 1 and 100 using np.random.randint()
(set a seed of 42 for reproducibility). Then:
a) Find the mean, median, standard deviation, min, and max.
b) Sort the array in descending order.
c) Find the indices of the 3 largest values using np.argsort().
d) Normalize the array so all values lie between 0 and 1
""";

In [88]:
np.random.seed(42)
arr = np.random.randint(1,101,15)
print(arr)
# A
print("Mean = ",arr.mean())
print("Median = ",np.median(arr))
print("std = ",arr.std())
print("Min = ",arr.min())
print("Max = ",arr.max())

#B
des = np.sort(arr[::-1])
print("desending= ",des)

#c
top3_indices = np.argsort(arr)[-3:][::-1]

print("Top 3 indices:", top3_indices)
print("Top 3 values:", arr[top3_indices])

#D # revise
normalized = (arr - arr.min()) / (arr.max() - arr.min())

print("Normalized array:", normalized)

[ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22]
Mean =  58.06666666666667
Median =  72.0
std =  31.4843170836247
Min =  3
Max =  100
desending=  [  3  15  21  22  24  52  61  72  75  75  83  87  88  93 100]
Top 3 indices: [11  1 10]
Top 3 values: [100  93  88]
Normalized array: [0.50515464 0.92783505 0.12371134 0.71134021 0.59793814 0.18556701
 0.82474227 0.86597938 0.74226804 0.74226804 0.87628866 1.
 0.21649485 0.         0.19587629]


# Section C — Pandas Basics

In [89]:
"""
7. Create a Pandas DataFrame from the dictionary below and perform the following:
data = { "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"], "Age": [23, 21,
25, 22, 24], "Department": ["AI", "Data Science", "AI", "Web Dev", "Data
Science"], "Score": [88, 92, 79, 95, 67], }
a) Display the first 3 rows and the data types of each column.
b) Add a new column Grade based on Score (>=90 'A', >=75 'B', else 'C').
c) Sort the DataFrame by Score in descending order.
d) Filter rows where Department is 'AI'.
""";

In [2]:
import pandas as pd
data = { "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"], 
        "Age": [23, 21,25, 22, 24],
        "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
        "Score": [88, 92, 79, 95, 67], }
df = pd.DataFrame(data)
# A
print(df.head(3))
print(df.dtypes)
#B
def get_grade(score):
    if score >= 90:
        return "A"
    elif score >= 75:
        return "B"
    else:
        return "C"

df["Grade"] = df["Score"].apply(get_grade)

#C
sort_df = df.sort_values(by="Score",ascending = False)
print(sort_df)
#D
ai_df = df[df["Department"] == "AI"]
print(ai_df)


    Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
Name          object
Age            int64
Department    object
Score          int64
dtype: object
    Name  Age    Department  Score Grade
3  Meera   22       Web Dev     95     A
1  Priya   21  Data Science     92     A
0  Aarav   23            AI     88     B
2  Karan   25            AI     79     B
4  Sahil   24  Data Science     67     C
    Name  Age Department  Score Grade
0  Aarav   23         AI     88     B
2  Karan   25         AI     79     B


In [3]:
"""

8. Using the same DataFrame from Q7:
a) Group by Department and find the average Score for each.
b) Find the row with the highest Score using idxmax().
c) Rename the column Score to Marks.
d) Drop the Age column and display the resulting DataFrame.
""";

In [15]:
data = { "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"], 
        "Age": [23, 21,25, 22, 24],
        "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
        "Score": [88, 92, 79, 95, 67], }
df= pd.DataFrame(data)
print(df)
#A
avg = df.groupby("Department")["Score"].mean()
print("\naverage=",avg)
#b
high_score= df.loc[df["Score"].idxmax()]

print("\nRow with Highest Score:")
print(high_score)
#c
rename = df.rename(columns= {"Score": "Marks"})
print("\nData feames afte renaming\n",rename)

#D
df_dropped = df.drop(columns = ["Age"])
print("\nAfter deleting Age\n",df_dropped)

    Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
3  Meera   22       Web Dev     95
4  Sahil   24  Data Science     67

average= Department
AI              83.5
Data Science    79.5
Web Dev         95.0
Name: Score, dtype: float64

Row with Highest Score:
Name            Meera
Age                22
Department    Web Dev
Score              95
Name: 3, dtype: object

Data feames afte renaming
     Name  Age    Department  Marks
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
3  Meera   22       Web Dev     95
4  Sahil   24  Data Science     67

After deleting Age
     Name    Department  Score
0  Aarav            AI     88
1  Priya  Data Science     92
2  Karan            AI     79
3  Meera       Web Dev     95
4  Sahil  Data Science     67


In [16]:
"""
9. Create a DataFrame with some missing values as shown below and handle them:
import numpy as np data = { "Product": ["Pen", "Notebook", "Eraser",
"Sharpener", "Ruler"], "Price": [10, np.nan, 5, 8, np.nan], "Stock": [100, 50,
np.nan, 30, 20], }
a) Check the number of missing values in each column using isnull().sum().
b) Fill missing Price values with the column mean.
c) Drop rows where Stock is still missing.
d) Save the cleaned DataFrame to a CSV file named cleaned_products.csv without the index
""";

In [36]:
import pandas as pd
import numpy as np

data = {
    "Product": ["Pen", "Notebook", "Eraser", "Sharpener", "Ruler"],
    "Price": [10, np.nan, 5, 8, np.nan],
    "Stock": [100, 50, np.nan, 30, 20]
}

df = pd.DataFrame(data)

# a) Count missing values
print(df.isnull().sum())

# b) Fill missing Price values with mean
df["Price"] = df["Price"].fillna(df["Price"].mean())

# c) Drop rows where Stock is missing
df = df.dropna(subset=["Stock"])

# d) Save cleaned DataFrame to CSV
df.to_csv("cleaned_products.csv", index=False)

print(df)

Product    0
Price      2
Stock      1
dtype: int64
     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0


In [37]:
"""
10. Read the CSV file created in Q9 (cleaned_products.csv) back into a new DataFrame and:
a) Print its shape and column names.
b) Add a new column Total_Value as Price multiplied by Stock.
c) Use describe() to print summary statistics of the numeric columns.
d) Wrap the file reading step in a try-except block to handle the case where the file does not
exist (FileNotFoundError).
""";

In [1]:
import pandas as pd

try:
    df = pd.read_csv("cleaned_products.csv")

    # a) 
    print("Shape of DataFrame:", df.shape)
    print("Column Names:", list(df.columns))

    # b) 
    df["Total_Value"] = df["Price"] * df["Stock"]

    print("\nDataFrame with Total_Value column:")
    print(df)

    # c) 
    print("\nSummary Statistics:")
    print(df.describe())

except FileNotFoundError:
    print("Error: 'cleaned_products.csv' file does not exist.")

Shape of DataFrame: (4, 3)
Column Names: ['Product', 'Price', 'Stock']

DataFrame with Total_Value column:
     Product      Price  Stock  Total_Value
0        Pen  10.000000  100.0  1000.000000
1   Notebook   7.666667   50.0   383.333333
2  Sharpener   8.000000   30.0   240.000000
3      Ruler   7.666667   20.0   153.333333

Summary Statistics:
           Price       Stock  Total_Value
count   4.000000    4.000000     4.000000
mean    8.333333   50.000000   444.166667
std     1.122167   35.590261   382.500303
min     7.666667   20.000000   153.333333
25%     7.666667   27.500000   218.333333
50%     7.833333   40.000000   311.666667
75%     8.500000   62.500000   537.500000
max    10.000000  100.000000  1000.000000
