In [2]:
#numpy


In [3]:
%pip install numpy

   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.5 MB 10.5 MB/s eta 0:00:02
   ---------- ----------------------------- 3.1/12.5 MB 10.8 MB/s eta 0:00:01
   ---------------- ----------------------- 5.0/12.5 MB 10.0 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.5 MB 10.5 MB/s eta 0:00:01
   ------------------------------- -------- 9.7/12.5 MB 10.6 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.5 MB 11.0 MB/s eta 0:00:01
   ---------------------------------------- 12.5/12.5 MB 9.4 MB/s  0:00:01
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [5]:
#creating arrays

In [6]:
sample_arr = np.array([1,2,3,4])

In [7]:
sample_arr

array([1, 2, 3, 4])

In [11]:
sample_arr2 = np.array((1,2,3,4,5))

In [13]:
sample_arr2

array([1, 2, 3, 4, 5])

In [15]:
# 2D array (a matrix) with 2 rows and 2 column

In [18]:
sample_arr3= np.array([[1,2],[3,4]])

In [19]:
sample_arr3

array([[1, 2],
       [3, 4]])

In [23]:
sample_arr4 = np.array([[2,4],[3,4],[5,6]])

In [24]:
sample_arr4

array([[2, 4],
       [3, 4],
       [5, 6]])

In [25]:
# 3D tensor (2 matrix,each with 2 rows and  2 column)

In [29]:
sample_tensor_3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [30]:
sample_tensor_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
sample_tensor_4 = np.array([[[4,8],[34,56]],[[54,78],[56,78]]])

In [48]:
sample_tensor_4.ndim

3

In [32]:
sample_tensor_4

array([[[ 4,  8],
        [34, 56]],

       [[54, 78],
        [56, 78]]])

In [34]:
# 0 dimenstional array(scaler) ex - 5
# 1D array (vector) [1,2,3,4]
#2D array (matrix) [rows and column]
# 3d array (tensor) (page,rows,column)

In [35]:
#array properties

In [36]:
sample_arr = np.array([[1,2,3],[4,5,6]])

In [37]:
sample_arr


array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
#checkk shape

In [39]:
sample_arr.shape

(2, 3)

In [40]:
# dimensions

In [41]:
sample_arr.ndim

2

In [42]:
#total elements

In [44]:
sample_arr.size

6

In [46]:
# data type

In [47]:
sample_arr.dtype

dtype('int64')

In [49]:
sample_array = np.array(([[[4,8],[34,56]],[[54,78],[56,78]]]))

In [50]:
sample_array.dtype

dtype('int64')

In [51]:
sample_array.ndim

3

In [52]:
sample_array.size

8

In [53]:
sample_array.shape

(2, 2, 2)

In [54]:
# special Arrays


In [56]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [61]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [64]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [70]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [2]:
import numpy as np
np.arange(1,20,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [3]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#Indexiing and slicing

In [4]:

sample_array = np.array([10,20,30,40])

In [5]:
sample_array

array([10, 20, 30, 40])

In [6]:
sample_array[0]

np.int64(10)

In [7]:
sample_array[2]

np.int64(30)

In [8]:
sample_array[-1]

np.int64(40)

In [9]:
#slicing

In [10]:

sample_array[1:3]

array([20, 30])

In [11]:
# Array Operations

In [12]:

a = np.array([1,2,3])

In [13]:
b = np.array ([4,5,6])

In [14]:
a

array([1, 2, 3])

In [15]:
b

array([4, 5, 6])

In [16]:
a+b

array([5, 7, 9])

In [17]:
a-b

array([-3, -3, -3])

In [18]:
a*b

array([ 4, 10, 18])

In [19]:
a/b

array([0.25, 0.4 , 0.5 ])

In [20]:
a = np.array([10,20,30])
b = np.array([40,50,60])

In [21]:
a

array([10, 20, 30])

In [22]:
b

array([40, 50, 60])

In [23]:
a+b

array([50, 70, 90])

In [24]:
a-b

array([-30, -30, -30])

In [25]:
a*b

array([ 400, 1000, 1800])

In [26]:
a/b

array([0.25, 0.4 , 0.5 ])

In [27]:
# Mathematical Function

In [29]:
sample_array = np.array([1,4,9])

In [30]:
sample_array

array([1, 4, 9])

In [31]:

np.sqrt(sample_array)

array([1., 2., 3.])

In [32]:

arr = np.array([34,56,90])
arr

array([34, 56, 90])

In [33]:
np.sqrt(arr)

array([5.83095189, 7.48331477, 9.48683298])

In [34]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [35]:

np.exp(arr)

array([5.83461743e+14, 2.09165950e+24, 1.22040329e+39])

In [36]:

np.log(sample_array)

array([0.        , 1.38629436, 2.19722458])

In [37]:
np.log(arr)

array([3.52636052, 4.02535169, 4.49980967])

In [38]:

arr1 = np.array([100,213,454])

In [39]:
np.log(arr1)

array([4.60517019, 5.36129217, 6.1180972 ])

In [40]:
# Statistical Functions

In [41]:
sample_array = np.array([1,2,3,4,5])


In [42]:
sample_array

array([1, 2, 3, 4, 5])

In [43]:

np.mean(sample_array)

np.float64(3.0)

In [44]:
np.median(sample_array)

np.float64(3.0)

In [45]:
np.std(sample_array)

np.float64(1.4142135623730951)

In [46]:
np.min(sample_array)


np.int64(1)

In [47]:
np.max(sample_array)


np.int64(5)

In [48]:
# Reshaping Arrays


In [49]:
arr = np.arange(0,6)


In [50]:
arr

array([0, 1, 2, 3, 4, 5])

In [53]:
reshaped = arr.reshape(2,3)


In [54]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [55]:
# Flattening 


In [56]:
arr = np.array([[1,2],[3,4]])


In [57]:
arr

array([[1, 2],
       [3, 4]])

In [58]:
arr.flatten()


array([1, 2, 3, 4])

In [59]:
arr =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])


In [60]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
arr.flatten()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [62]:
# Joining Arrays


In [63]:
arr1 = np.array([1,2,3,4,5])


In [64]:
arr2 = np.array([6,7,8,9,10])


In [67]:

np.concatenate((arr1,arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
# Splitting Arrays


In [69]:
arr = np.array([1,2,3,4,5])


In [70]:
arr

array([1, 2, 3, 4, 5])

In [72]:
np.array_split(arr,2)


[array([1, 2, 3]), array([4, 5])]

In [73]:
np.split(arr,5) # only for equal split


[array([1]), array([2]), array([3]), array([4]), array([5])]

In [74]:
# Random Module


In [75]:
np.random.rand(3)


array([0.90266534, 0.10036157, 0.30031957])

In [77]:
np.random.randint(1,10,5)


array([8, 1, 7, 6, 9], dtype=int32)

In [78]:
# Axis Concept


In [79]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])


In [80]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [81]:
# for addition
# coloum = 0
# row = 1

In [82]:

np.sum(arr,axis=0)

array([ 7,  9, 11, 13, 15])

In [83]:
np.sum(arr,axis = 1)


array([15, 40])

In [84]:
# NaN (not a number) & Missing values


In [85]:
sample_array = np.array([1,np.nan,3])
sample_array

array([ 1., nan,  3.])

In [86]:
np.isnan(sample_array)


array([False,  True, False])

In [89]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([2,4,5,6])
arr1 + arr2



array([12, 24, 35, 46])

In [90]:
arr1 - arr2


array([ 8, 16, 25, 34])

In [91]:
arr1 * arr2

array([ 20,  80, 150, 240])

In [92]:
arr1 % arr2

array([0, 0, 0, 4])